{% set name = "websockify" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/novnc/websockify/archive/v{{ version }}.tar.gz
  sha256: 37448ec992ef626f29558404cf6535592d02894ec1d5f0990a8c62621b39a967

build:
  # Independent of Python version, but rebind.so depends on OS
  number: 0
  entry_points:
    - websockify = websockify.websocketproxy:websockify_init
  script: {{ PYTHON }} -m pip install . -vv  # [win]
  # Use build.sh for Linux
  missing_dso_whitelist:
    - /lib64/libc.so.6
    - /lib64/libdl.so.2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
    - make  # [linux]
  host:
    - pip
    - python
  run:
    - numpy
    - python
    - requests
    - jwcrypto
    - redis-py

test:
  imports:
    - websockify
  commands:
    - websockify --help
    # The rebind library is only supported on Linux
    - websockify 12345 -- ls  # [linux]

about:
  home: https://github.com/novnc/websockify
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING
  summary: Websockify is a WebSocket to TCP proxy/bridge.
  description: |
    Websockify is a WebSocket to TCP proxy/bridge.
    This allows a browser to connect to any application/server/service.
  doc_url: https://github.com/novnc/websockify
  dev_url: https://github.com/novnc/websockify

extra:
  recipe-maintainers:
    - manics
